#pragma once
#include <string>
#include <list>
#include <iostream>
#include <map>
#include <set>
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <filesystem>
#include <unordered_map>

using std::string;
using std::cout;
using std::list;
using std::map;
using std::set;
using std::unordered_map;
using std::pair;
using std::make_pair;
using std::vector;
using std::endl;
using std::ifstream;
using std::stringstream;
using std::to_string;